ALTER TABLE "health_records" ADD COLUMN "muac" real;--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "breakfast" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "fruit_intake" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "vegetables" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "protein_intake" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "junk_food" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "sugary_drinks" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "water_intake" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "physical_activity" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "screen_time" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "outdoor_play" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "sleep_hours" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "smoking" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "alcohol" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "chronic_disease" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "frequent_fever" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "weight_loss" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "poor_appetite" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "repeated_infection" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "hospitalisation" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "medication" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "stress" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "mood" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "concentration" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "bullying" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "pallor" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "dental_caries" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "poor_oral_hygiene" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "vision_problem" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "hair_changes" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "skin_changes" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "vaccination_complete" varchar(20);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "deworming" varchar(20);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "hand_hygiene" varchar(50);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "dental_checkup" varchar(10);--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "vision_screening" varchar(10);
